CREATE TABLE restaurant_reservations (
    reservation_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    guest_name      VARCHAR2(200) NOT NULL,
    phone_number    VARCHAR2(30) NOT NULL,
    email           VARCHAR2(320),
    reservation_at  TIMESTAMP NOT NULL,
    party_size      NUMBER(3) NOT NULL,
    status          VARCHAR2(20) DEFAULT 'CONFIRMED' NOT NULL,
    special_requests VARCHAR2(1000),
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT restaurant_reservations_pk PRIMARY KEY (reservation_id),
    CONSTRAINT restaurant_reservations_party_ck CHECK (party_size > 0),
    CONSTRAINT restaurant_reservations_status_ck
        CHECK (status IN ('CONFIRMED', 'SEATED', 'CANCELLED'))
);

INSERT INTO restaurant_reservations
    (guest_name, phone_number, email, reservation_at, party_size, status, special_requests)
VALUES
    ('Aiko Tanaka', '090-1234-5678', 'aiko.tanaka@example.com',
     TIMESTAMP '2026-10-10 18:30:00', 2, 'CONFIRMED', 'Window seat requested');

INSERT INTO restaurant_reservations
    (guest_name, phone_number, email, reservation_at, party_size, status, special_requests)
VALUES
    ('Kenji Sato', '080-2345-6789', NULL,
     TIMESTAMP '2026-10-10 19:00:00', 4, 'CONFIRMED', 'One vegetarian guest');

INSERT INTO restaurant_reservations
    (guest_name, phone_number, email, reservation_at, party_size, status, special_requests)
VALUES
    ('Mika Suzuki', '070-3456-7890', 'mika.suzuki@example.com',
     TIMESTAMP '2026-10-11 12:00:00', 3, 'SEATED', NULL);

INSERT INTO restaurant_reservations
    (guest_name, phone_number, email, reservation_at, party_size, status, special_requests)
VALUES
    ('Daichi Watanabe', '090-4567-8901', NULL,
     TIMESTAMP '2026-10-11 19:30:00', 2, 'CANCELLED', 'Cancelled by guest');

INSERT INTO restaurant_reservations
    (guest_name, phone_number, email, reservation_at, party_size, status, special_requests)
VALUES
    ('Yui Nakamura', '080-5678-9012', 'yui.nakamura@example.com',
     TIMESTAMP '2026-10-12 18:00:00', 5, 'CONFIRMED', NULL);

COMMIT;
